version: "3"

services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:1323:1323"
    networks:
      - default

networks:
  default: